name: MacOS Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13
    
    env:
      QT_VERSION: "6.6.1"
      MACOSX_DEPLOYMENT_TARGET: "12.0"
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        modules: 'qtmultimedia qtpositioning qtwebchannel'
        tools: 'tools_cmake tools_ninja'
        cache: true
        aqtversion: '==3.1.*'

    - name: Install dependencies
      run: |
        brew update
        brew install cmake pkg-config
        brew install libgit2
        brew install fftw
        brew install ffmpeg
        brew install webp
        brew install jpeg-xl
        brew install sdl2
        brew install libsoxr

    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake
      working-directory: ./build
      env:
        Qt6_DIR: ${{ env.Qt6_DIR }}
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
          -DCMAKE_INSTALL_RPATH="@executable_path/../Frameworks"
    
    - name: Build
      working-directory: ./build
      run: |
        cmake --build . --config Release -j$(sysctl -n hw.ncpu)
    
    - name: Package
      working-directory: ./build
      run: |
        cd output
        
        # Setup app structure
        mkdir -p Vagyojaka.app/Contents/Frameworks
        chmod -R 755 Vagyojaka.app
        
        # Function to copy libraries
        copy_lib_with_deps() {
          local lib=$1
          [ ! -f "$lib" ] && return
          
          local basename=$(basename "$lib")
          local dest="Vagyojaka.app/Contents/Frameworks/$basename"
          
          if [ ! -f "$dest" ]; then
            cp -f -P "$lib" "Vagyojaka.app/Contents/Frameworks/"
            chmod 755 "$dest"
            install_name_tool -id "@rpath/$basename" "$dest"
            
            otool -L "$lib" | tail -n +2 | awk '{print $1}' | grep -E '^(/usr/local/|/opt/homebrew/)' | while read dep; do
              local depbase=$(basename "$dep")
              install_name_tool -change "$dep" "@rpath/$depbase" "$dest"
              
              for prefix in /usr/local/lib /opt/homebrew/lib /usr/local/opt/*/lib /opt/homebrew/opt/*/lib; do
                [ -f "$prefix/$depbase" ] && copy_lib_with_deps "$prefix/$depbase"
              done
            done
          fi
        }

        # Copy FFmpeg libraries
        for lib in $(find "$(brew --prefix ffmpeg)/lib" -name "*.dylib"); do
          copy_lib_with_deps "$lib"
        done

        # Copy other libraries
        for formula in webp jpeg-xl sdl2 libsoxr libgit2 fftw; do
          for lib in $(find "$(brew --prefix $formula)/lib" -name "*.dylib"); do
            copy_lib_with_deps "$lib"
          done
        done

        # Fix executable references
        chmod 755 Vagyojaka.app/Contents/MacOS/Vagyojaka
        otool -L Vagyojaka.app/Contents/MacOS/Vagyojaka | tail -n +2 | awk '{print $1}' | grep -E '^(/usr/local/|/opt/homebrew/)' | while read dep; do
          install_name_tool -change "$dep" "@rpath/$(basename "$dep")" Vagyojaka.app/Contents/MacOS/Vagyojaka
        done

        # Create DMG
        macdeployqt Vagyojaka.app -verbose=2 -always-overwrite
        macdeployqt Vagyojaka.app -verbose=2 -dmg -always-overwrite

        # Handle DMG for release
        if [ -f Vagyojaka.dmg ]; then
          chmod 644 Vagyojaka.dmg
          [ "$GITHUB_REF" = refs/tags/* ] && mv Vagyojaka.dmg "Vagyojaka-${{ github.ref_name }}-macos.dmg"
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Vagyojaka-macOS
        path: build/output/Vagyojaka*.dmg

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/output/Vagyojaka*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
