name: MacOS Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    
    env:
      QT_VERSION: "6.6.1"
      MACOSX_DEPLOYMENT_TARGET: "12.0"
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Intel Homebrew
      run: |
        cd /usr/local
        sudo mkdir homebrew
        sudo chown -R $(whoami) homebrew
        curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
        eval "$(/usr/local/homebrew/bin/brew shellenv)"
        brew update --force --quiet
        echo "PATH=/usr/local/homebrew/bin:$PATH" >> $GITHUB_ENV
        chmod -R g+rwx /usr/local/homebrew

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        modules: 'qtmultimedia qtpositioning qtwebchannel'
        tools: 'tools_cmake tools_ninja'
        cache: true
        aqtversion: '==3.1.*'

    - name: Install dependencies
      run: |
        brew install cmake pkg-config
        brew install libgit2
        brew install fftw
        brew install ffmpeg

    - name: Switch Xcode version
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.2.app

    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake
      working-directory: ./build
      env:
        Qt6_DIR: ${{ env.Qt6_DIR }}
        PKG_CONFIG_PATH: "/usr/local/homebrew/lib/pkgconfig"
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
          -DCMAKE_OSX_ARCHITECTURES="x86_64" \
          -DCMAKE_LIBRARY_PATH="/usr/local/homebrew/lib" \
          -DCMAKE_INCLUDE_PATH="/usr/local/homebrew/include"
    
    - name: Build
      working-directory: ./build
      run: |
        cmake --build . --config Release -j$(sysctl -n hw.ncpu)
    
    - name: Package
      working-directory: ./build
      run: |
        cd output
        
        # Update Info.plist
        cat > Vagyojaka.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>Vagyojaka</string>
            <key>CFBundleIconFile</key>
            <string>AppIcon.icns</string>
            <key>CFBundleIdentifier</key>
            <string>com.vagyojaka.app</string>
            <key>CFBundleName</key>
            <string>Vagyojaka</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${GITHUB_REF_NAME:-1.0.0}</string>
            <key>LSMinimumSystemVersion</key>
            <string>12.0</string>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        # Deploy Qt dependencies and create DMG
        macdeployqt Vagyojaka.app -verbose=2 -dmg -always-overwrite
        
        # Copy required x86_64 libraries
        mkdir -p Vagyojaka.app/Contents/Frameworks
        for lib in libgit2 libfftw3 libavformat libavcodec libavutil libavdevice; do
          if [ -f "/usr/local/homebrew/lib/${lib}*.dylib" ]; then
            cp /usr/local/homebrew/lib/${lib}*.dylib Vagyojaka.app/Contents/Frameworks/
          fi
        done
        
        # Rename DMG if this is a release
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          mv Vagyojaka.dmg "Vagyojaka-${{ github.ref_name }}-macos.dmg"
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Vagyojaka-macOS
        path: build/output/Vagyojaka*.dmg

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/output/Vagyojaka*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
