name: MacOS Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13
    
    env:
      QT_VERSION: "6.6.1"
      MACOSX_DEPLOYMENT_TARGET: "12.0"
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        modules: 'qtmultimedia qtpositioning qtwebchannel'
        tools: 'tools_cmake tools_ninja'
        cache: true
        aqtversion: '==3.1.*'

    - name: Install dependencies
      run: |
        brew update
        brew install cmake pkg-config
        brew install libgit2
        brew install fftw
        brew install ffmpeg
        brew install webp
        brew install jpeg-xl
        brew install sdl2
        brew install libsoxr
        brew install libx11
        brew install libxcb
        brew install libxau
        brew install libxdmcp
        brew install libxext
        brew install libxfixes

    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake
      working-directory: ./build
      env:
        Qt6_DIR: ${{ env.Qt6_DIR }}
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0
    
    - name: Build
      working-directory: ./build
      run: |
        cmake --build . --config Release -j$(sysctl -n hw.ncpu)
    
    - name: Package
      working-directory: ./build
      run: |
        cd output
        
        sudo chmod -R 755 Vagyojaka.app
        
        sudo tee Vagyojaka.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>Vagyojaka</string>
            <key>CFBundleIconFile</key>
            <string>AppIcon.icns</string>
            <key>CFBundleIdentifier</key>
            <string>com.vagyojaka.app</string>
            <key>CFBundleName</key>
            <string>Vagyojaka</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${GITHUB_REF_NAME:-1.0.0}</string>
            <key>LSMinimumSystemVersion</key>
            <string>12.0</string>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        sudo mkdir -p Vagyojaka.app/Contents/Frameworks
        sudo chmod 755 Vagyojaka.app/Contents/Frameworks
        
        # Copy all libraries and their dependencies
        copy_libs() {
          local lib="$1"
          local dest="$2"
          if [ -f "$lib" ]; then
            sudo cp -p "$lib" "$dest/"
            # Fix permissions
            sudo chmod 755 "$dest/$(basename "$lib")"
            # Get and copy dependencies
            otool -L "$lib" | tail -n +2 | cut -d' ' -f1 | while read -r dep; do
              if [[ "$dep" =~ ^(/usr/local/|/opt/homebrew/|@rpath/) ]]; then
                local depname=$(basename "$dep")
                for search_path in "/usr/local/lib" "/usr/local/opt/"*/lib "/opt/homebrew/lib" "/opt/homebrew/opt/"*/lib; do
                  if [ -f "$search_path/$depname" ]; then
                    copy_libs "$search_path/$depname" "$dest"
                    break
                  fi
                done
              fi
            done
          fi
        }
        
        # List of libraries to copy
        for lib in \
          libavcodec.*.dylib \
          libavdevice.*.dylib \
          libavfilter.*.dylib \
          libavformat.*.dylib \
          libavutil.*.dylib \
          libswresample.*.dylib \
          libswscale.*.dylib \
          libsharpyuv.*.dylib \
          libwebp.*.dylib \
          libwebpmux.*.dylib \
          libjxl.*.dylib \
          libjxl_cms.*.dylib \
          libgit2.*.dylib \
          libfftw3.*.dylib \
          libsoxr.*.dylib \
          libSDL2.*.dylib \
          libX11.*.dylib \
          libxcb.*.dylib \
          libxcb-shm.*.dylib \
          libxcb-shape.*.dylib \
          libxcb-xfixes.*.dylib \
          libXau.*.dylib \
          libXdmcp.*.dylib \
          libXext.*.dylib \
          libXfixes.*.dylib; do
          find "$(brew --prefix)" -name "$lib" -exec bash -c 'copy_libs "{}" "Vagyojaka.app/Contents/Frameworks"' \;
        done
        
        # Fix library paths
        sudo find Vagyojaka.app/Contents/Frameworks -name "*.dylib" -type f | while read -r lib; do
          sudo chmod 755 "$lib"
          sudo install_name_tool -id "@rpath/$(basename "$lib")" "$lib"
          otool -L "$lib" | tail -n +2 | cut -d' ' -f1 | while read -r dep; do
            if [[ "$dep" =~ ^(/usr/local/|/opt/homebrew/|@rpath/) ]]; then
              depname=$(basename "$dep")
              sudo install_name_tool -change "$dep" "@rpath/$depname" "$lib" || true
            fi
          done
        done
        
        # Run macdeployqt after fixing libraries
        sudo macdeployqt Vagyojaka.app -verbose=2 -dmg -always-overwrite
        
        if [[ -f Vagyojaka.dmg ]]; then
          sudo chmod 644 Vagyojaka.dmg
        fi
        
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          sudo mv Vagyojaka.dmg "Vagyojaka-${{ github.ref_name }}-macos.dmg"
          sudo chmod 644 "Vagyojaka-${{ github.ref_name }}-macos.dmg"
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Vagyojaka-macOS
        path: build/output/Vagyojaka*.dmg

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/output/Vagyojaka*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
